# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622257c27a7cf11476dbb5ded25f31ba5d3ae2cea1c9326b906e74be34ab1e81a8656e06dfee7c580bee4a6d597706dd8a78cd43e8a3fc89861692568d3782fe

test:
  secret_key_base: 8a9a245f63d6854841dc1ff80ad01195b4d0bc19854de0d7d7fa4e266ff0c377e6bfc0717cacfe9615bb04c63cea5b4345472c165b5af153e05ef854d7c18f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
